version: '3.5'

services:
  app-go:
    container_name: app-go
    build: .
    networks:
      - app-network
    volumes:
      - .:/app
    command: tail -f /dev/null


  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit-telefonica
    tty: true
    env_file:
      - .docker/rabbitamq/.env
    ports:
      - 8081:15672
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=root
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=root
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbit-data:
    driver: local
  elastic-data:
    driver: local
